change version of github Actions, try to make them work

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -9,33 +9,32 @@ on:
       - master
 
 jobs:
-  build:
+  docker:
+    timeout-minutes: 10
     runs-on: ubuntu-latest
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
 
-    - name: Set up Docker
-      uses: docker/setup-buildx-action@v2
-
-    - name: Install Docker Compose
+    - name: Build all Docker containers
       run: |
-        sudo apt-get update
-        sudo apt-get install -y docker-compose
+        docker compose -f docker-compose.yml build
 
-    - name: Build and run Docker containers
+    - name: Run the backend-test container
       run: |
-        docker compose -f docker-compose.yml up --build -d
+        docker compose -f docker-compose.yml up -d backend-test
 
-    - name: Run backend tests
+    - name: Wait for the backend-test container to finish
       run: |
-        docker-compose exec -T backend pytest ./tests
-
-    - name: Run frontend tests
-      run: |
-        docker-compose exec -T frontend npm run test
+        docker-compose logs -f backend-test
+        exit_code=$(docker wait $(docker-compose ps -q backend-test))
+        if [ "$exit_code" -ne 0 ]; then
+          echo "Backend test container failed with exit code $exit_code"
+          exit $exit_code
+        fi
 
     - name: Deploy
+      if: success()
       run: |
         # Add your deployment commands here
